{{ range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
  namespace: {{$.Values.namespace}}
  labels:
    environment: {{$.Values.environment}}
    app: {{.name}}
spec:
  replicas: {{.replicaCount}}
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: {{.name}}
          image: "{{ .image.repository }}:{{ .image.version }}"
          imagePullPolicy: {{.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{.containerPort}}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{.probes.initialDelaySeconds}}
            periodSeconds: {{.probes.periodSeconds}}
            httpGet:
              path: {{.probes.path}}
              port: {{.probes.port}}
          readinessProbe:
            initialDelaySeconds: {{.probes.initialDelaySeconds}}
            periodSeconds: {{.probes.periodSeconds}}
            httpGet:
              path: {{.probes.path}}
              port: {{.probes.port}}
          resources:
            limits:
              memory: "{{ .resources.limits.memory }}"
              cpu: "{{ .resources.limits.cpu }}"
          env:
            {{- range .env}}
            - name: "{{.name}}"
              value: "{{.value}}"
            {{- end}}
            {{- range .secretEnv}}
            - name: "{{.name}}"
              valueFrom:
                secretKeyRef:
                  name: "{{.secretKeyRef.name}}"
                  key: "{{.secretKeyRef.key}}"
            {{- end}}

{{ end }}
