---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: /frontend-vue
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
  name: ingress-app-root
  namespace: {{$.Values.namespace}}
spec:
  rules:
    - host: "{{ $.Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-vue
                port:
                  number: 80
