---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster
  namespace: {{$.Values.namespace}}
spec:
  replicas: {{$.Values.replicas}}
  secretName: mysql-secret
  podSpec:
    resources:
      requests:
        memory: 1G
        cpu: 512m
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
